POST http://localhost:3000/api/diaries
Content-Type: application/json

{
    "date": "2025-11-17",
    "weather": "sunny",
    "visibility": "ok",
    "comment": "Awesome day"
}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 88
etag: W/"58-/w+NWL6VEqgfiMG7OzY9BhknErk"
date: Sun, 04 May 2025 02:54:20 GMT
connection: close